### ISSUE TITLE
Default Position and Animation

### ISSUE THREAD

**Issue by kuraydev** [polyak01/IconSwitch#11]
Hello,
I love this library. Thank you for your effort :)
I can use this when I set the default one "left" and it works awesome with that. However, I want to set the default right one and get the animation from list to map by default.
I could not make it by myself.
Can you guide me how to do that?
Thank you :)

**Comment by polyak01** [comment]
@WrathChaos I do not support this library more, unfortunately. Maybe will do it in the future.
