### ISSUE TITLE
set statusbar color to trasparent

### ISSUE THREAD

**Issue by iceberg1369** [polyak01/IconSwitch#3]
Hello there,

I used your sample to implement iconswitch in my app. but by updating statusbar color the transparency is gone, and  navigation drawer falls behind the status bar. so how is it possible to make status bar transparent again?

thanks for your awesome job

**Comment by yarolegovich** [comment]
You should use `drawerLayout.setStatusBarBackgroundColor` instead of `window.setStatusBarColor`.

**Comment by iceberg1369** [comment]
drawer.setStatusBarBackgroundColor(Color.TRANSPARENT); didn't help.

**Comment by yarolegovich** [comment]
You should:
1. Never touch `window.setStatusBarColor` except if you call `window.setStatusBarColor(TRANSPARENT)`.
2. During the transition call `drawer.setStatusBarBackgroundColor(desiredColor)`

**Comment by iceberg1369** [comment]
drawer.setStatusBarBackgroundColor(desiredColor) just changes toolbar color. but this way status color remains untouched which makes app color ugly. so is there a way I could change statusbar color as well?

**Comment by yarolegovich** [comment]
If this changes color of the toolbar, you are doing something wrong in your layout. I can recommend only to make sure that you have `fitsSystemWindow=true` set.

**Comment by iceberg1369** [comment]
@yarolegovich I appreciate your help and time. I will update the issue as soon as I could a work around

**Comment by iceberg1369** [comment]
I use CoordinatorLayout as my root view. and adding fitsSystemWindow=false to CoordinatorLayout  and fitsSystemWindow=true to drawer layout resolved the issue.
![icocc](https://cloud.githubusercontent.com/assets/4116434/25307091/505c6f64-27b0-11e7-8594-acd9b44e1f6b.png)
