### ISSUE TITLE
Crash when using vector drawables on Android 4.4

### ISSUE THREAD

**Issue by Dwite** [polyak01/IconSwitch#4]
Crash when using vector drawables on Android 4.4

**Comment by Shadkirill** [comment]
Use VectorDrawableCompat

**Comment by Dwite** [comment]
@Shadkirill I do use VectorDrawablesCompat, but this library supports setting icons only through XML, and getting drawable from style attribute not in the proper way for API < 21, so that won't help.

**Comment by Shadkirill** [comment]
Did you find solution?

**Comment by Dwite** [comment]
@Shadkirill yeah, fixed it in https://github.com/polyak01/IconSwitch/pull/5

Or you can wrap your vector drawable into layer-list and use layer-list drawable as src

**Comment by vkrissz** [comment]
This bugfix was not uploaded to maven. Can you release a new version of it?
